server:
  port: 8088

spring:
  application:
    name: demo5
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  datasource:
    url: jdbc:mysql://localhost:3306/zpt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    com.example.demo.dao: trace
  pattern:
    console: '%p%m%n'

